### Submit evaluation
POST http://localhost:3000/user/evaluation
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJvbGFucmV3YWp1QGdtYWlsLmNvbSIsIl9pZCI6IjY0MDhiMjc1ODYyM2FlYTYwNzI1NTViNyIsImlhdCI6MTY3ODcwODQ5MH0.-rrNGSay57PmYYuFdFd2rEnybjeh3bewANMlZMbdRK4

{
    "checkInDate": "July 10, 2022",
    "checkOutDate": "July 14, 2022",
    "firstTime": "no",
    "frontDeskOfficePerformance": 5
}

### Get evaluation
GET http://localhost:3000/user/get-evaluation?emailAddress=olanrewaju@gmail.com&all=false
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJvbGFucmV3YWp1QGdtYWlsLmNvbSIsIl9pZCI6IjY0MDhiMjc1ODYyM2FlYTYwNzI1NTViNyIsImlhdCI6MTY3ODcwODQ5MH0.-rrNGSay57PmYYuFdFd2rEnybjeh3bewANMlZMbdRK4

### Get feedbacks
GET http://localhost:3000/user/contact-us
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJvbGFucmV3YWp1QGdtYWlsLmNvbSIsIl9pZCI6IjY0MDhiMjc1ODYyM2FlYTYwNzI1NTViNyIsImlhdCI6MTY3ODcwODQ5MH0.-rrNGSay57PmYYuFdFd2rEnybjeh3bewANMlZMbdRK4

### get newsletters
GET http://localhost:3000/user/newsletter
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJvbGFucmV3YWp1QGdtYWlsLmNvbSIsIl9pZCI6IjY0MDhiMjc1ODYyM2FlYTYwNzI1NTViNyIsImlhdCI6MTY3ODcwODQ5MH0.-rrNGSay57PmYYuFdFd2rEnybjeh3bewANMlZMbdRK4