# signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Yusuf",
    "lastName": "Olanrewaju",
    "emailAddress": "olanrewaju@gmail.com",
    "password": "1234567"
}